shp_path: /app/data/uploads/1b9dc295/G97_64000_U0201_2015.shp
output_dir: /app/data/results
products:
  CHIRPS:
    ee_collection: UCSB-CHG/CHIRPS/DAILY
    bands:
      - precipitation
    statistics:
      - sum
    scale: 5566
    start_date: '2024-06-01'
    end_date: '2024-12-31'
